### PR TITLE
BFB-141: Rotate towards wall direction on wall run

### PR DESCRIPTION
**Pull request by unoctium1**
**JIRA Ticket**
https://perigongames.atlassian.net/browse/BFB-141

**Description**
Now pushes the player towards the wall direction when wall running, also some small code cleanup on wall running

### CODE REVIEW

**Comment by m4rtint** [comment]
It feels very good this time around.

**Comment by m4rtint** [comment]
How difficult is it to keep the max wall run speed even when looking closer to the wall?

**Comment by unoctium1** [comment]
Do you just mean ensure the velocity is independent of where the camera is looking?

**Comment by m4rtint** [comment]
> Do you just mean ensure the velocity is independent of where the camera is looking?

Yeah, more of a curiosity, not sure if it'll be better or worse.

**Comment by unoctium1** [comment]
> > Do you just mean ensure the velocity is independent of where the camera is looking?
> 
> Yeah, more of a curiosity, not sure if it'll be better or worse.

It should be pretty easy, I'll try making it toggleable and see how well it works

**Comment by unoctium1** [comment]
Tried it out, its maybe harder than I'd thought. Seems like its much harder to stay attached to the wall and I'm not really sure why

**Comment by m4rtint** [comment]
> Tried it out, its maybe harder than I'd thought. Seems like its much harder to stay attached to the wall and I'm not really sure why

yeah i think it's better to remove it. 

I wonder  if there's a way to use a curve for the Look along the wall motion, so even if it's super fast look speed, it won't be too jerky.

**Comment by unoctium1** [comment]
> I wonder if there's a way to use a curve for the Look along the wall motion, so even if it's super fast look speed, it won't be too jerky.

What do you mean? Like a curve for the rotation?

**Comment by m4rtint** [comment]
> > I wonder if there's a way to use a curve for the Look along the wall motion, so even if it's super fast look speed, it won't be too jerky.
> 
> What do you mean? Like a curve for the rotation? 

So currently when rotating towards forward,  it's pretty much a linear curve, I'm wondering if it's possible to do another type of curve.

**Comment by unoctium1** [comment]
> So currently when rotating towards forward, it's pretty much a linear curve, I'm wondering if it's possible to do another type of curve.

I'm not sure how feasible that would be, its currently just getting the difference between the heading and current and adding the rotation each frame. Adding a curve would be a pretty drastic restructuring, and I'm not sure it would still respond to mouse input as well

**Review by m4rtint — APPROVED** [review]

**Pull request merged**
