### PR TITLE
BFB-406: Weapon View Custom Pass Fix

### PR DESCRIPTION
**Pull request by m4rtint**
**JIRA Ticket**
https://perigongames.atlassian.net/browse/BFB-83

**Description**
- Reference:
https://www.intetic.com/blogs/unity-hdrp-render-object-on-top-of-everything/

- Added 2 custom passes
- remove Weapon Camera
I DON'T KNOW THE DETAILS,  BUT YOU CAN READ WHAT I FOLLOWED ^^^

**Screenshots / GIFs**
Screen Shot 2022-08-10 at 10 23 36 PM

https://user-images.githubusercontent.com/5779541/184054658-1ba2a162-d32c-41f4-b1f2-6168346bdf90.mov

### CODE REVIEW

**Review by unoctium1 — COMMENTED** [review]
Tested, and it looks like the issues in #198 are still present - weapon blurs a bit and has strange transparency. Also I was able to get it to clip through some objects

**Comment by m4rtint** [comment]
> Tested, and it looks like the issues in #198 are still present - weapon blurs a bit and has strange transparency. Also I was able to get it to clip through some objects

I just made some changes
- made Lit -> Both deferred and forwarded -> Quality > Lit Shader Mode
- Added in Both Pistol and AR, just to make sure it's rendering weapons correctly. 
- Set one of the custom passes to be after post processing.

**Comment by unoctium1** [comment]
https://user-images.githubusercontent.com/31762637/184065797-cb2099aa-1b2d-4877-a21a-ad40e6429ebe.mp4

I'm still seeing the transparency issues (very faint, but does seem to be there)- also the shotgun and scout rifle are rendering inside out now

**Comment by m4rtint** [comment]
> BForBoss.-.MS2_RaceCourse.-.Windows.Mac.Linux.-.Unity.2021.3.0f1.Personal._DX11_.2022-08-10.21-39-41.mp4 
> I'm still seeing the transparency issues (very faint, but does seem to be there)- also the shotgun and scout rifle are rendering inside out now

- Set the injection point to be `After Opaque and normal`. 
- And fixed the inside out rendering (previous changes didn't commit properly)

Screen Shot 2022-08-11 at 9 29 26 AM

Try it again?

**Comment by unoctium1** [comment]
@m4rtint The inside out is fixed, but it seems like other things are broken now - VFX in the scene was causing screen tearing, smoke from gunshots was causing massive rendering issues. It also seemed like the transparency issue might still be a problem, where the gun is ever so slightly translucent

**Comment by m4rtint** [comment]
> @m4rtint The inside out is fixed, but it seems like other things are broken now - VFX in the scene was causing screen tearing, smoke from gunshots was causing massive rendering issues. It also seemed like the transparency issue might still be a problem, where the gun is ever so slightly translucent

Okay updated the custom pass to be `Before Post processing`. That should fix the VFX in the scene. 
The only thing I can't fix is the slight translucency. 

However, it'll show the VFX on the scene. (Slow motion and dash). This might be the current compromise to be able to see the VFX since it's now a blocker to the HUD VFX

**Comment by m4rtint** [comment]
And also i've been testing on MT_Sandbox and Sandbox
Not MS2 - since there's a lot of redundant components on it currently.

**Review by unoctium1 — APPROVED** [review]
Like you mentioned, translucency is still a slight issue - however its vague enough we could just bug it for now and merge this in, it seems like it works pretty well at this point

**Pull request merged**
