### PR TITLE
BFB-447: Store 1 and 3 second iteration

### PR DESCRIPTION
**Pull request by mchang19**
**JIRA Ticket**
https://perigongames.atlassian.net/browse/BFB-447

**Description**
*[insert here]*

**Screenshots / GIFs**
*[insert here]*

### CODE REVIEW

**Comment by m4rtint** [comment]
Do you have any images of store 1 / 3?

**Comment by m4rtint** [comment]
image

**Comment by m4rtint** [comment]
image

**Comment by csweet22** [comment]
221012 Store1_3

**Review by m4rtint — APPROVED** [review]

**Review by Gursaanj — APPROVED** [review]

**Pull request merged**
