### PR TITLE
New AR model

### PR DESCRIPTION
**Pull request by mchang19**
**JIRA Ticket**
https://perigongames.atlassian.net/browse/BFB-[TICKET NUMBER]

**Description**
- Updated AR model placed into assets with textures and material

**Screenshots / GIFs**
221102 AR Final

### CODE REVIEW

**Comment by Gursaanj** [comment]
@mchang19 what were the changes made to `WaveSandbox.unity`

**Comment by mchang19** [comment]
@Gursaanj  sorry, there weren't any changes to the WaveSandbox! some values might have gotten changed when i was pulling the model into the scene to check how it looked. removed the updated file from this pr.

**Comment by csweet22** [comment]
This looks good to me! I'll change the current assault rifle to use this mesh and material once I'm back at my computer. I'd do it at my laptop, but it keeps crashing on Unity 😫

**Review by Gursaanj — APPROVED** [review]

**Comment by Gursaanj** [comment]
@mchang19 looks good to merge! @m4rtint would you agree

**Comment by m4rtint** [comment]
> @mchang19 looks good to merge! @m4rtint would you agree

I thought we're waiting for Cole. But it looks good. 
image

**Review by m4rtint — APPROVED** [review]

**Pull request merged**
