### PR TITLE
BFB-134 : Sandbox SceneTemplate

### PR DESCRIPTION
**Pull request by Gursaanj**
**JIRA Ticket**
https://perigongames.atlassian.net/browse/BFB-134

**Description**
Created a scene template in which users can create a new scene with all the bare bone assets/prefabs needed to play/build a scene with a working Character and Pause menu Functionality.

Refer to the gif below as to how to create a new Scene from this template (will be put onto Jira ticket as well). 

Note that this dialog does not exist from creating a scene based on the project inspector (i.e. right-click -> New Scene). So for now, the only way is to click on File -> New Scene

**Screenshots / GIFs**
Create from New Scene Template

### CODE REVIEW

**Comment by m4rtint** [comment]
You left a message refering to leaving out DebugView, If you think that's a good judgement call and you tested it out and it works better that way, then that's okay 👍

**Review by m4rtint — APPROVED** [review]
Everything looks good. 

Maybe ping @unoctium1  just incase,

**Review by unoctium1 — CHANGES_REQUESTED** [review]
This looks mostly good to me, could you replace the AudioListener on the main camera with an FMOD Event listener though? I can also make that change quickly if you're prefer

**Comment by Gursaanj** [comment]
> This looks mostly good to me, could you replace the AudioListener on the main camera with an FMOD Event listener though? I can also make that change quickly if you're prefer

Good Catch, just updated the template scene

**Review by unoctium1 — APPROVED** [review]
lgtm

**Pull request merged**
