### PR TITLE
BFB-265: Fixed VFX Start Bug and Fixed Duplicate VFX Textures in Scene Template

### PR DESCRIPTION
**Pull request by csweet22**
**JIRA Ticket**
https://perigongames.atlassian.net/browse/BFB-265

**Description**
VFX no longer fire as soon as the scene starts. VFX components' **Initial Event Name** are now empty rather than OnPlay.

There was an issue where whenever a new scene was created from the Sandbox with Weapon Scene Template, a folder would be created with duplicates of all of the VFX Textures the muzzle flashes depend on. The duplicates are not actually used and can be deleted. They will no longer be cloned when creating a new scene from this template.

Also changed one small properties in material shader.

### CODE REVIEW

**Comment by csweet22** [comment]
I'm not sure why this branch has all of my commits from BFB-264, but it does.

**Comment by m4rtint** [comment]
> I'm not sure why this branch has all of my commits from BFB-264, but it does.

Did you start working on this from your old branch?

**Comment by m4rtint** [comment]
Everything looks good. Just wondering, if  there's a different use case between the 
MaterialsExample.scene
and
MatTestScene.scene

**Comment by csweet22** [comment]
> Everything looks good. Just wondering, if there's a different use case between the MaterialsExample.scene and MatTestScene.scene

The MaterialsExample scene acts as an example of the materials for others to see how they work while the MatTestScene is just a place for me to test and experiment when I'm creating new materials.

**Comment by csweet22** [comment]
> > I'm not sure why this branch has all of my commits from BFB-264, but it does.
> 
> Did you start working on this from your old branch?

Yeah it was probably something like that.

**Comment by m4rtint** [comment]
> > > I'm not sure why this branch has all of my commits from BFB-264, but it does.
> > 
> > 
> > Did you start working on this from your old branch?
> 
> Yeah it was probably something like that.

yeah that's why the commits are stacked. It's fine :)

**Review by m4rtint — APPROVED** [review]

**Pull request merged**
